version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  foodie-database:
    container_name: foodie-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: yesol23/foodie-database
    environment:
      - MYSQL_DATABASE=foodie-database
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d        # MySQL 설정 파일이 있습니다.
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)